### ISSUE TITLE
🐳[Docker] Injecting env vars bug with some plugins names

### ISSUE THREAD

**Issue by ScreamZ** [kuzzleio/kuzzle#1429]
I'm experiencing an issue with docker env vars, @ballinette was able to reproduce.

Given the following `docker-compose.yml`
```yml
services:
  kuzzle:
    image: kuzzleio/plugin-dev:1.9.1
    command: /run-dev.sh
    volumes:
      - "./run-dev.sh:/run-dev.sh"
      - "./install-plugins.sh:/install-plugins.sh"
      - "./pm2.json:/config/pm2.json"
      - "./ffgym-plugin:/var/app/plugins/enabled/ffgym-plugin"
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    sysctls:
      - net.core.somaxconn=8192
    depends_on:
      - redis
      - elasticsearch
    ports:
      - "9229:9229"
      - "7512:7512"
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_plugins__ffgym-plugin-sso__apiHost=https://myhost.com/ExtUserRest/rest
      - NODE_ENV=development
      - DEBUG=kuzzle:plugins
```

My plugin is called `ffgym-plugin-sso` and contains an `apiHost` parameter.

Because I'm using `- kuzzle_plugins__ffgym-plugin-sso__apiHost=https://myhost.com/ExtUserRest/rest` this configuration is not getting injected.

It seems that plugins containing `-`(dashe) can't get injected by such method.

Without dashes, it seems to work.

Regards

**Comment by benoitvidis** [comment]
Hi @ScreamZ , thank you for your submission.
Actually, this is not related to `Kuzzle` or even the `rc` module which is used to parse these vars.

Environment variables cannot contain a dash:

```shell
$ export foo-bar=1
export: not valid in this context: foo-bar
```

I am afraid the only solution is either to rename the plugin or to mount a rc file with your custom configuration within the container:

rcDev
```json
{
  "plugins": {
     "ffgym-plugin-sso": {
        "apiHost": "https://myhost.com/ExtUserRest/rest"
     }
  }
}
```
```yaml
services:
  kuzzle:
    image: kuzzleio/plugin-dev:1.9.1
    [..]
    volumes:
       - ./rcDev:/var/app/.kuzzlerc
```
