### ISSUE TITLE
Kuzzle Docker not loading server

### ISSUE THREAD

**Issue by rjpalermo1** [kuzzleio/kuzzle#347]
Just trying out Kuzzle this morning and followed quick start.  Created

```
kuzzle:
  image: kuzzleio/kuzzle:latest
  ports:
    - "7512:7512"
    - "7511:7511"
  links:
    - elasticsearch
    - redis
    
kuzzleBo:
  image: kuzzleio/bo:latest
  ports:
    - "3000:3000"
  links:
    - kuzzle

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:2.2
```

Then docker-compose up -d and then this: 

```
KuzzleServer-0 Starting Kuzzle Server
KuzzleServer-0 Plugin kuzzle-plugin-auth-passport-local started
KuzzleServer-0 Plugin kuzzle-plugin-logger started
KuzzleServer-0 error: [2016-07-19T11:33:39.124Z]: log:error: [proxyBroker] Error while trying to connect to ws://api:7331 [getaddrinfo ENOTFOUND api api:7331]
KuzzleServer-0       ==> RECONNECTING IN 1000ms
KuzzleWorker-1 info: [2016-07-19T11:33:39.590Z]: internalBroker:*: Connected to Kuzzle server
KuzzleWorker-1 info: [2016-07-19T11:33:39.591Z]: internalBroker:*: Re-registering room: worker-write-queue
KuzzleWorker-1 info: [2016-07-19T11:33:39.592Z]: internalBroker:*: Re-registering room: remote-actions-queue
KuzzleWorker-1 info: [2016-07-19T11:33:39.594Z]: internalBroker:*: Re-registering room: remote-actions-queue-92
KuzzleWorker-1 warn: [2016-07-19T11:33:39.595Z]: log:warn: [internalBroker] Node is connected while it was previously already.
KuzzleServer-0 error: [2016-07-19T11:33:40.171Z]: log:error: [proxyBroker] Error while trying to connect to ws://api:7331 [getaddrinfo ENOTFOUND api api:7331]
KuzzleServer-0       ==> RECONNECTING IN 1000ms
KuzzleServer-0 error: [2016-07-19T11:33:41.223Z]: log:error: [proxyBroker] Error while trying to connect to ws://api:7331 [getaddrinfo ENOTFOUND api api:7331]
```

**Comment by rjpalermo1** [comment]
So I just used the docker-compose in this git repo and all is working.

Seems you just need to update your Quick Start docs here:

http://kuzzle.io/guide/#make-your-own-compose-file

Here goes...I didn't see or read anything yet about a document store ie, Mongo or rethink so I'll start digging.  You should consider a little blurb on how this is handled, or if it can be handled.

- RP

**Comment by scottinet** [comment]
Good catch. The docker compose file in the documentation is outdated. I will replace the example with a direct link to our official docker compose file, preventing the documentation to be outdated again.

Thanks!

**Comment by scottinet** [comment]
Fixed. The documentation will be updated in a few moments.

In the meantime, you can fix your own `docker-compose.yml` by adding the following lines to it:

```yaml
proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
```
