### ISSUE TITLE
Impossible to start Kuzzle stack docker

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle#891]
I followed the step 1 on your website Kuzze.io.

I have all the pre-requisites okay. But at the step 
```[i]Starting Kuzzle ``` nothing happened and I never had the line ```Kuzzle is running```

I went further, renamed `kuzzle-docker-compose.yml` to  #`docker-compose.yml` then ran the command : 
`docker-compose up`

And after a few seconds, I have the error : 

```[ℹ] Starting Kuzzle server
kuzzle_1         | Elasticsearch ERROR: 2017-06-24T12:35:18Z
kuzzle_1         |   Error: Request error, retrying
kuzzle_1         |   GET http://localhost:9200/_mapping => connect ECONNREFUSED 127.0.0.1:9200
kuzzle_1         |       at Log.error (/var/app/node_modules/elasticsearch/src/lib/log.js:225:56)
kuzzle_1         |       at checkRespForFailure (/var/app/node_modules/elasticsearch/src/lib/transport.js:246:18)
kuzzle_1         |       at HttpConnector.<anonymous> (/var/app/node_modules/elasticsearch/src/lib/connectors/http.js:157:7)
kuzzle_1         |       at ClientRequest.bound (/var/app/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)
kuzzle_1         |       at emitOne (events.js:96:13)
kuzzle_1         |       at ClientRequest.emit (events.js:188:7)
kuzzle_1         |       at Socket.socketErrorListener (_http_client.js:309:9)
kuzzle_1         |       at emitOne (events.js:96:13)
kuzzle_1         |       at Socket.emit (events.js:188:7)
kuzzle_1         |       at emitErrorNT (net.js:1277:8)
kuzzle_1         |       at _combinedTickCallback (internal/process/next_tick.js:80:11)
kuzzle_1         |       at process._tickDomainCallback (internal/process/next_tick.js:128:9)
kuzzle_1         | Elasticsearch WARNING: 2017-06-24T12:35:18Z
kuzzle_1         |   Unable to revive connection: http://localhost:9200/
kuzzle_1         | Elasticsearch WARNING: 2017-06-24T12:35:18Z
kuzzle_1         |   No living connections
kuzzle_1         | es service is not connected Error
kuzzle_1         |     at ServiceUnavailable.KuzzleError (/var/app/node_modules/kuzzle-common-objects/lib/errors/kuzzleError.js:17:19)
kuzzle_1         |     at new ServiceUnavailable (/var/app/node_modules/kuzzle-common-objects/lib/errors/serviceUnavailableError.js:6:15)
kuzzle_1         |     at handleError (/var/app/lib/services/internalEngine/index.js:487:28)
kuzzle_1         |     at client.indices.getMapping.catch.error (/var/app/lib/services/internalEngine/index.js:423:23)
kuzzle_1         |     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
kuzzle_1         | App [KuzzleServer] with id [0] and pid [688], exited with code [1] via signal [SIGINT]
kuzzle_1         | Starting execution sequence in -fork mode- for app name:KuzzleServer id:0
kuzzle_1         | App name:KuzzleServer id:0 online
```

To check if the problem is from ES, I tweaked the docker-compose.yml to forward the ports 9200 and 9300 outside of docker network : 
``` 
 elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      # disable xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
```
And the result outside of docker network
```
$ curl http://localhost:9200
{
  "name" : "qGm6-2W", #
  "cluster_name" : "kuzzle",
  "cluster_uuid" : "zzgRjWBkQFKTJI1YVB6u5Q",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
```

And also, to be sure I went into kuzzle docker : 
```
$ docker exec -ti backend_kuzzle_1 su
root@6a4690d58088:/var/app# curl http://172.18.0.2:9200
{
  "name" : "qGm6-2W",
  "cluster_name" : "kuzzle",
  "cluster_uuid" : "zzgRjWBkQFKTJI1YVB6u5Q",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
```
and the docker networking is good inside dockers : 
```
root@6a4690d58088:/var/app# curl http://elasticsearch:9200
{
  "name" : "qGm6-2W",
  "cluster_name" : "kuzzle",
  "cluster_uuid" : "zzgRjWBkQFKTJI1YVB6u5Q",
  "version" : {
    "number" : "5.4.1",
    "build_hash" : "2cfe0df",
    "build_date" : "2017-05-29T16:05:51.443Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.1"
  },
  "tagline" : "You Know, for Search"
}
```

Where is the .kuzzlerc or default.config.js to tweak it and put elasticsearch as host instead of localhost?

**Comment by Tyki** [comment]
I found the kuzzle instance in /var/app.

To make it works, I had to create a .kuzzlerc : 

```
{
  "services": {
    "db": {
      "backend": "elasticsearch",
      "aliases": ["storageEngine"],
      "client": {
        "host": "http://elasticsearch:9200",
        "apiVersion": "5.x"
      }
    }
  }
}
```
and mount the .kuzzlerc in the docker-compose.yml : 
```
kuzzle:
    image: kuzzleio/kuzzle
    volumes:
      - /home/gara/workspace/backend/.kuzzlerc:/var/app/.kuzzlerc
.....
```

And after a docker-compose up, I finally have : 
```
kuzzle_1         | [✔] Kuzzle server ready
kuzzle_1         | [ℹ] There is no administrator user yet. You can use the CLI or the back-office to create one.
kuzzle_1         | [ℹ] Entering no-administrator mode: everyone has administrator rights.
```

**Comment by Tyki** [comment]
I think you should put a .kuzzlerc 'or tweak the default.config.js but I dont think it's a good idea) in the docker stack to be able to properly connect to ES

**Comment by stafyniaksacha** [comment]
Seen with @Tyki, installation issue is about [`setup.sh`](https://github.com/kuzzleio/kuzzle-build/blob/master/setup.sh)

**Comment by AnthonySendra** [comment]
Hello,

Your Kuzzle tries to access to 127.0.0.1:9200 which is not the right place to find your elasticsearch. The problems comes probably from your `docker-compose.yml` file. The right one looks like:

```
version: '2'

services:
  proxy:
    image: kuzzleio/proxy
    ports:
      - "7512:7512"

  kuzzle:
    image: kuzzleio/kuzzle
    cap_add:
      - SYS_PTRACE
    depends_on:
      - proxy
      - redis
      - elasticsearch
    environment:
      - kuzzle_services__db__client__host=http://elasticsearch:9200
      - kuzzle_services__internalCache__node__host=redis
      - kuzzle_services__memoryStorage__node__host=redis
      - kuzzle_services__proxyBroker__host=proxy
      - NODE_ENV=production

  redis:
    image: redis:3.2

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - cluster.name=kuzzle
      # disable xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false

```

In Kuzzle service, you can see the environment variable `kuzzle_services__db__client__host=http://elasticsearch:9200`. Our `docker-compose.yml` was recently updated. You can find the new one at http://kuzzle.io/docker-compose.yml.

If you used the `setup.sh` file, the problem is probably solved because this script use the file at http://kuzzle.io/docker-compose.yml
